"""Shared PR-body rendering + fingerprint dedup for the efficiency mission.

Both GitHubEfficiencyPRCreator and BitbucketEfficiencyPRCreator render the same
body from a perf report, so the markdown lives here. The body also embeds a
machine-readable fingerprint marker that lets the PR creators avoid opening a
duplicate PR for a finding that already has one open (P4).
"""
from __future__ import annotations

import re
from typing import Any

# Embedded in every efficiency PR body so we can detect, on a later run, which
# findings already have an open PR and skip them.
FINGERPRINT_MARKER_RE = re.compile(r"<!--\s*janus-fingerprints:\s*([0-9a-f,]+)\s*-->")


EFFICIENCY_PR_BODY_TEMPLATE = """\
## JANUS Efficiency Mission — Autonomous Refactor

This PR was generated by the Efficiency Brain after a profile -> refactor -> verify cycle.
Every finding below has a **verified** refactoring: outputs are identical AND the new code \
is measurably faster in the benchmark sandbox.

### Impact Summary

| Metric | Value |
|--------|-------|
| Findings verified | {verified_count} |
| Projected savings / year | **${annual_dollars:,.2f}** |
| CO2 avoided / year | **{annual_co2_g:,.0f} g** |

{fingerprint_marker}

---

{findings_section}
"""

EFFICIENCY_FINDING_TEMPLATE = """\
### {idx}. {title}

| Field | Value |
|-------|-------|
| Category | `{category}` |
| Language | `{language}` |
| Severity | `{severity}` |
| Location | `{location}` |
| Rule | `{rule_id}` |
| Complexity before | `{complexity_before}` |
| Complexity after | `{complexity_after}` |
| Speedup | `{speedup_x:.1f}×` |
| Memory saved / call | `{memory_mb:.3f} MB` |
| Calls / year (assumed) | `{calls_per_year:,}` |
| Annual savings | `${annual_dollars:,.2f}` |
| CO2 avoided | `{annual_co2_g:,.0f} g/yr` |

**Why this matters**

{description}

<details>
<summary>Before</summary>

```
{before}
```
</details>

<details>
<summary>After (verified correct + faster)</summary>

```
{after}
```
</details>

**Explanation:** {explanation}
{runner_up}"""


def _loc(loc: dict[str, Any]) -> str:
    return f"{loc.get('file', '')}:{loc.get('start_line', '')}-{loc.get('end_line', '')}"


def _complexity(f: dict[str, Any], ref: dict[str, Any], key: str) -> str:
    return (ref.get(key)
            or (f.get("metadata") or {}).get(key)
            or "?")


def render_efficiency_body(findings: list[dict[str, Any]], report: dict[str, Any]) -> str:
    sections: list[str] = []
    fingerprints: list[str] = []
    for i, f in enumerate(findings, 1):
        loc = f.get("location") or {}
        ref = f.get("refactoring") or {}
        bm = f.get("benchmark") or {}
        sav = f.get("savings") or {}
        fp = f.get("fingerprint") or ""
        if fp:
            fingerprints.append(fp)
        runner_up = ""
        if ref.get("runner_up_note"):
            runner_up = (
                f"\n<details>\n<summary>Alternative candidate considered "
                f"({ref.get('runner_up_note')})</summary>\n\n```\n"
                f"{ref.get('runner_up_code', '')}\n```\n</details>\n")
        sections.append(
            EFFICIENCY_FINDING_TEMPLATE.format(
                idx=i,
                title=f.get("title") or f.get("category", ""),
                category=f.get("category", ""),
                language=f.get("language", "python"),
                severity=f.get("severity", ""),
                location=_loc(loc),
                rule_id=f.get("rule_id") or "n/a",
                complexity_before=_complexity(f, ref, "complexity_before"),
                complexity_after=_complexity(f, ref, "complexity_after"),
                speedup_x=float(bm.get("speedup_x") or 0.0),
                memory_mb=float(sav.get("memory_saved_mb_per_call") or 0.0),
                calls_per_year=int(sav.get("calls_per_year") or 0),
                annual_dollars=float(sav.get("annual_dollars") or 0.0),
                annual_co2_g=float(sav.get("annual_co2_grams") or 0.0),
                description=f.get("description") or "(no description)",
                before=(ref.get("location") or {}).get("snippet", ref.get("original_code", "")),
                after=ref.get("refactored_code", ""),
                explanation=ref.get("explanation", ""),
                runner_up=runner_up,
            )
        )
    marker = f"<!-- janus-fingerprints: {','.join(fingerprints)} -->" if fingerprints else ""
    return EFFICIENCY_PR_BODY_TEMPLATE.format(
        verified_count=len(findings),
        annual_dollars=float(report.get("total_annual_dollars") or 0.0),
        annual_co2_g=float(report.get("total_annual_co2_grams") or 0.0),
        fingerprint_marker=marker,
        findings_section="\n---\n".join(sections),
    )


def fingerprints_in_body(body: str) -> set[str]:
    """Extract the set of finding fingerprints embedded in an existing PR body."""
    m = FINGERPRINT_MARKER_RE.search(body or "")
    if not m:
        return set()
    return {x for x in m.group(1).split(",") if x}


def dedup_findings(
    verified: list[dict[str, Any]],
    open_pr_bodies: list[str],
) -> tuple[list[dict[str, Any]], list[str]]:
    """Return (findings_needing_a_pr, skipped_fingerprints). A finding is skipped
    when its fingerprint already appears in an open PR body."""
    already: set[str] = set()
    for body in open_pr_bodies:
        already |= fingerprints_in_body(body)
    remaining = [f for f in verified if (f.get("fingerprint") or "") not in already]
    skipped = [f.get("fingerprint", "") for f in verified
               if (f.get("fingerprint") or "") in already]
    return remaining, skipped
