from __future__ import annotations

import argparse
import json
import logging
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    from github import Github
    import urllib3 as _urllib3
    _urllib3.disable_warnings(_urllib3.exceptions.InsecureRequestWarning)
except ImportError:
    Github = None  # type: ignore[assignment]


log = logging.getLogger("security_brain.pr")


PR_BODY_TEMPLATE = """\
## Agentic Security Platform — Autonomous Fix

This PR was generated by the Security Brain after an exploit → patch → validate cycle.
Every finding below has a **confirmed** working PoC and a **validated** fix (tests pass AND \
the exploit no longer reproduces in the sandbox).

### Summary
{summary}

---

{findings_section}
"""

FINDING_TEMPLATE = """\
### {idx}. {title}

| Field        | Value |
|--------------|-------|
| Category     | `{category}` |
| Severity     | `{severity}` |
| Location     | `{location}` |
| Rule         | `{rule_id}` |
| Status       | `{status}` |
| Exploitability | `{exploitability:.2f}` |

**Description**

{description}

**Proof of Concept (executed inside sandbox)**

- Payload: `{payload}`
- Evidence: `{evidence}`

<details>
<summary>Exploit script</summary>

```python
{script}
```
</details>

**Fix**

{fix_explanation}

References: {references}

<details>
<summary>Before</summary>

```
{before}
```
</details>

<details>
<summary>After</summary>

```
{after}
```
</details>
"""


class GitHubPRCreator:
    def __init__(self, repo_slug: str, token: str | None = None, base_branch: str = "main"):
        if Github is None:
            raise RuntimeError("PyGithub not installed. pip install PyGithub")
        self.repo_slug = repo_slug
        self.base_branch = base_branch
        self.token = token or os.environ.get("GITHUB_TOKEN")
        if not self.token:
            raise RuntimeError("GITHUB_TOKEN not set")
        try:
            from github import Auth as GithubAuth
            self.gh = Github(auth=GithubAuth.Token(self.token), verify=False)
        except (ImportError, TypeError):
            # Older PyGithub (<2.0) doesn't have Auth; fall back to positional arg.
            self.gh = Github(self.token, verify=False)

    def create_pr_from_report(self, repo_root: Path, report: dict[str, Any]) -> str:
        validated = [
            f for f in report.get("findings", [])
            if f.get("status") == "validated" and f.get("patch")
        ]
        if not validated:
            log.info("no validated findings; skipping PR")
            return ""

        run_id = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        branch = f"security/autofix-{run_id}"
        self._push_branch(repo_root, branch)
        body = self._render_body(validated)
        repo = self.gh.get_repo(self.repo_slug)
        pr = repo.create_pull(
            title=f"[SecurityBrain] Auto-fix {len(validated)} validated finding(s)",
            body=body,
            head=branch,
            base=self.base_branch,
        )
        log.info("opened PR %s", pr.html_url)
        return pr.html_url

    def _push_branch(self, repo_root: Path, branch: str) -> None:
        env_git = {
            "GIT_AUTHOR_NAME": "SecurityBrain",
            "GIT_AUTHOR_EMAIL": "securitybrain@aci.local",
            "GIT_COMMITTER_NAME": "SecurityBrain",
            "GIT_COMMITTER_EMAIL": "securitybrain@aci.local",
            # Bypass corporate TLS-inspection proxy for git HTTPS operations.
            "GIT_SSL_NO_VERIFY": "true",
        }
        merged_env = {**os.environ, **env_git}
        commands = [
            ["git", "checkout", "-B", branch],
            ["git", "add", "-A"],
            ["git", "commit", "-m", f"security: autonomous fixes for {branch}"],
            ["git", "push", "-u", "origin", branch, "--force-with-lease"],
        ]
        for cmd in commands:
            subprocess.run(cmd, cwd=repo_root, check=True, env=merged_env)

    def _render_body(self, findings: list[dict[str, Any]]) -> str:
        sections: list[str] = []
        for i, f in enumerate(findings, 1):
            exp = f.get("exploit") or {}
            patch = f.get("patch") or {}
            evidence = (exp.get("actual_signal") or "").splitlines()
            sections.append(
                FINDING_TEMPLATE.format(
                    idx=i,
                    title=f.get("title") or f.get("category", ""),
                    category=f.get("category", ""),
                    severity=f.get("severity", ""),
                    location=_loc(f.get("location", {})),
                    rule_id=f.get("rule_id") or "n/a",
                    status=f.get("status", ""),
                    exploitability=float(f.get("exploitability") or 0.0),
                    description=f.get("description") or "(no description)",
                    payload=exp.get("payload", ""),
                    evidence=evidence[0] if evidence else "",
                    script=exp.get("script", ""),
                    fix_explanation=patch.get("explanation", ""),
                    references=", ".join(patch.get("references") or []) or "n/a",
                    before=patch.get("original_code", ""),
                    after=patch.get("patched_code", ""),
                )
            )
        summary = "\n".join(
            f"- `{f.get('category', '')}` ({f.get('severity', '')}) at `{_loc(f.get('location', {}))}`"
            for f in findings
        )
        return PR_BODY_TEMPLATE.format(summary=summary, findings_section="\n---\n".join(sections))


class GitHubEfficiencyPRCreator:
    """Raises a PR for verified efficiency refactorings, skipping findings that
    already have an open PR (fingerprint dedup, P4)."""

    def __init__(self, repo_slug: str, token: str | None = None, base_branch: str = "main"):
        if Github is None:
            raise RuntimeError("PyGithub not installed. pip install PyGithub")
        self.repo_slug = repo_slug
        self.base_branch = base_branch
        self.token = token or os.environ.get("GITHUB_TOKEN")
        if not self.token:
            raise RuntimeError("GITHUB_TOKEN not set")
        # verify=False: corporate TLS-inspection proxy at ACI breaks cert chains.
        try:
            from github import Auth as GithubAuth
            self.gh = Github(auth=GithubAuth.Token(self.token), verify=False)
        except (ImportError, TypeError):
            self.gh = Github(self.token, verify=False)

    def create_pr_from_perf_report(self, repo_root: Path, report: dict[str, Any]) -> str:
        from .efficiency_pr_body import dedup_findings, render_efficiency_body

        verified = [
            f for f in report.get("findings", [])
            if f.get("status") == "verified" and f.get("refactoring")
        ]
        if not verified:
            log.info("no verified efficiency findings; skipping PR")
            return ""

        repo = self.gh.get_repo(self.repo_slug)
        open_bodies = self._open_efficiency_pr_bodies(repo)
        remaining, skipped = dedup_findings(verified, open_bodies)
        if skipped:
            log.info("efficiency PR dedup: %d finding(s) already have an open PR", len(skipped))
        if not remaining:
            log.info("all verified findings already have open PRs; skipping")
            return ""

        run_id = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        branch = f"efficiency/autofix-{run_id}"
        self._push_branch(repo_root, branch)
        body = render_efficiency_body(remaining, report)
        pr = repo.create_pull(
            title=f"[JANUS] Efficiency refactors — {len(remaining)} verified finding(s)",
            body=body,
            head=branch,
            base=self.base_branch,
        )
        log.info("opened efficiency PR %s", pr.html_url)
        return pr.html_url

    def _open_efficiency_pr_bodies(self, repo) -> list[str]:
        bodies: list[str] = []
        try:
            for pr in repo.get_pulls(state="open"):
                if (pr.head.ref or "").startswith("efficiency/autofix-"):
                    bodies.append(pr.body or "")
        except Exception as e:  # network / perms — dedup is best-effort
            log.warning("efficiency PR dedup: could not list open PRs: %s", e)
        return bodies

    def _push_branch(self, repo_root: Path, branch: str) -> None:
        env_git = {
            "GIT_AUTHOR_NAME": "JANUSEfficiencyBrain",
            "GIT_AUTHOR_EMAIL": "janus-efficiency@aci.local",
            "GIT_COMMITTER_NAME": "JANUSEfficiencyBrain",
            "GIT_COMMITTER_EMAIL": "janus-efficiency@aci.local",
            "GIT_SSL_NO_VERIFY": "true",
        }
        merged_env = {**os.environ, **env_git}
        for cmd in [
            ["git", "checkout", "-B", branch],
            ["git", "add", "-A"],
            ["git", "commit", "-m", f"efficiency: verified refactors for {branch}"],
            ["git", "push", "-u", "origin", branch, "--force-with-lease"],
        ]:
            subprocess.run(cmd, cwd=repo_root, check=True, env=merged_env)


def _loc(loc: dict[str, Any]) -> str:
    return f"{loc.get('file', '')}:{loc.get('start_line', '')}-{loc.get('end_line', '')}"


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    parser = argparse.ArgumentParser(description="Create a GitHub PR from a SecurityBrain report.")
    parser.add_argument("--repo", required=True, type=Path, help="Path to the source repo (git worktree)")
    parser.add_argument("--report", required=True, type=Path, help="Path to report.json produced by the orchestrator")
    parser.add_argument("--slug", required=True, help="GitHub owner/name")
    parser.add_argument("--base", default="main", help="Base branch for the PR")
    args = parser.parse_args()

    report = json.loads(args.report.read_text(encoding="utf-8"))
    pr = GitHubPRCreator(repo_slug=args.slug, base_branch=args.base)
    url = pr.create_pr_from_report(args.repo, report)
    if url:
        print(url)


if __name__ == "__main__":
    main()
